name: flutter_fb
description: use_for_flutter_firebase

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  carousel_slider: ^4.1.1

  flutter_linkify:
  url_launcher:

  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.2
  firebase_messaging: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  logger: ^1.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
